spring.application.name=gamedb
spring.profiles.active=dev
spring.data.mongodb.uri=${DB_CONNECTION_STRING:mongodb://admin:password@mongodb:27017/gamedb?authSource=admin}
spring.data.mongodb.database=gamedb
spring.main.allow-bean-definition-overriding=true
spring.data.mongodb.auto-index-creation=true
JWT_SECRET_KEY=${APP_JWT_SECRET}