# Dev profile
cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173
spring.data.mongodb.uri=mongodb://admin:password@localhost:27018/gamedb?authSource=admin
spring.data.mongodb.database=gamedb
JWT_SECRET_KEY=584a0a20d65af30d8825a3865fb668646df9d32b1b8404435176272035cfb22e
logging.level.kev.gamedb=DEBUG
